services:
  - type: web
    name: rag-chatbot
    runtime: python
    pythonVersion: "3.13.1"
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn backend.core.app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false






